<?php

namespace Xaben\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Request;
/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findAllByPage(Request $request, $topicId, $page, $paginator)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT p,t,pt,f,u FROM XabenForumBundle:Post p JOIN p.topic t JOIN p.posttext pt JOIN t.forum f JOIN p.poster u WHERE t.id = :topicId ORDER BY t.id DESC";
        $query = $em->createQuery($dql)
                    ->setParameter('topicId', $topicId);

        $pagination = $paginator->paginate(
                $query,
                $request->query->get('page', $page),
                10
        );

        return $pagination;
    }
}
