<?php

namespace Xaben\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PosttextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosttextRepository extends EntityRepository
{
}
