<?php

namespace Xaben\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Request;
/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends EntityRepository
{

    public function findAllByPage(Request $request, $forumId, $page, $paginator)
    {
        $em = $this->getEntityManager();
        $dql = 'SELECT t,f,p,du,bu,du1,bu1 
            FROM XabenForumBundle:Topic t 
            JOIN t.forum f 
            JOIN t.poster du 
            JOIN du.baseuser bu 
            JOIN t.last_post p 
            JOIN p.poster du1 
            JOIN du1.baseuser bu1 
            WHERE f.id = :forumId 
            ORDER BY t.id DESC
        ';
        $result = $em->createQuery($dql)
                    ->setParameter('forumId', $forumId)
                    ->getArrayResult();

        $pagination = $paginator->paginate(
                $result,
                $request->query->get('page', $page),
                10
        );

        return $pagination;
    }
}
