<?php

namespace Xaben\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Request;
/**
 * UserdataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserdataRepository extends EntityRepository
{
/*
    public function findAllByPage(Request $request, $forumId, $page, $paginator)
    {
        $em = $this->getEntityManager();
        $dql = 'SELECT t,f,p,u,u1,pt FROM XabenForumBundle:Topic t JOIN t.forum f JOIN t.poster u JOIN t.last_post p JOIN p.posttext pt JOIN p.poster u1 WHERE f.id = :forumId ORDER BY t.id DESC';
        $query = $em->createQuery($dql)
                    ->setParameter('forumId', $forumId);

        $pagination = $paginator->paginate(
                $query,
                $request->query->get('page', $page),
                10
        );

        return $pagination;
    }*/
}
